// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCA_P34rPl8a6sZlgfcKXkvTfFgGMMskoY',
    appId: '1:952988594143:android:a672f6ef944ffb82841e6a',
    messagingSenderId: '952988594143',
    projectId: 'whatsapp-clone-68a6c',
    databaseURL: 'https://whatsapp-clone-68a6c.firebaseio.com',
    storageBucket: 'whatsapp-clone-68a6c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSQz6NG3SkrBs5v1T_rlAaxiUmTboNdtM',
    appId: '1:952988594143:ios:88a0699c943f4c4a841e6a',
    messagingSenderId: '952988594143',
    projectId: 'whatsapp-clone-68a6c',
    databaseURL: 'https://whatsapp-clone-68a6c.firebaseio.com',
    storageBucket: 'whatsapp-clone-68a6c.appspot.com',
    androidClientId: '952988594143-j0kfl61obu9dsu1p4qens5lt85i68h9l.apps.googleusercontent.com',
    iosBundleId: 'com.example.persistVenturesAsn',
  );
}
